name: audio_flux
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ^3.6.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_recorder:
    path: ../flutter_recorder
  flutter_soloud:
    path: ../flutter_soloud
  shader_buffers: ^1.1.1
  meta: ^1.16.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

  very_good_analysis: ^6.0.0

flutter:
