name: audio_flux
description: >-
  Audio visualizer which uses flutter_soloud and
  flutter_recorder to acquire the audio data and
  display them using a CustomPainter or
  shader_buffer to render them to shaders.
version: 1.0.0
homepage: https://github.com/alnitak/audio_flux
publish_to: none
topics:
  - audio
  - visualizer
  - shader

screenshots:
  - description: "shader"
    path: img/shader.png

environment:
  sdk: ^3.6.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_recorder: ^1.1.0
    # path: ../flutter_recorder
  flutter_soloud: ^3.1.0
    # path: ../flutter_soloud
  shader_buffers: ^1.1.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

  very_good_analysis: ^6.0.0

flutter:
